blended_version = 3.4

# Configuration is automatically generated by Blended, feel free to edit any values below
website_name = "Blended Software"
website_description = "Software demo websitew"
website_description_long = "" # Use for things like author bio on a blog
website_license = "GPL3.0"
author_name = "John Roper"
website_language = "en"
home_page_list = "yes"

# The following values are used for FTP uploads
ftp_server = "localhost"
ftp_username = "user"
ftp_password = "pass"
ftp_port = 21
ftp_upload_path = "public_html/myWebsite"
